version: "3.9"

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - ~/data/db_data:/var/lib/mysql
    networks:
      - wpsite
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build:  ./requirements/wordpress
    image:  wordpress
    env_file:
      - .env
    volumes:
      - ~/data/wp_data:/var/www/html/wordpress
    networks:
      - wpsite
    restart: always

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    env_file:
      - .env
    volumes:
      - ~/data/wp_data:/var/www/html/wordpress
    networks:
      - wpsite
    ports:
      - 80:80
      - 443:443
    restart: always

networks:
  wpsite:

# volumes:

#   db_data:
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/Users/michele/data/db-data'

#   wp_data:
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/Users/michele/data/wp-data'

